### ISSUE TITLE
Policy Representation

### ISSUE THREAD

**Issue by markkho** [markkho/msdm#5]
How should we revamp the policy representation to be more generic? One idea is to make it more like a numpy array where you "index" things by state or action.

**Comment by cgc** [comment]
definitely think making the most of python's syntax to make policy access simpler/easier makes a lot of sense. I think `__getitem__` (`policy[s]`) is a cool solution. `__call__` is another option, but seems less ideal in way that I'm struggling to articulate.

**Comment by markkho** [comment]
`TabularPolicy` extends `dict` now, so this is resolved in https://github.com/markkho/msdm/commit/554bcd27db5994b9e340e5fd3746c0c60a63c90b
