### ISSUE TITLE
Uniform distribution

### ISSUE THREAD

**Issue by markkho** [markkho/msdm#59]
The behavior for the `UniformDistribution` is inconsistent when it receives multiple copies of the same element. For instance:

```python
from msdm.core.distributions import UniformDistribution, DictDistribution

dist1 = UniformDistribution('abb')
dist2 = DictDistribution({'a': 1/3, 'b': 2/3})
dist1 == dist2 # False
dist1.prob('b') == dist2.prob('b') # False
```

I see two options and lean towards the 2nd:
1. Enforce that UniformDistribution receives unique elements.
2. Automatically bin equivalent elements when constructing a UniformDistribution and return a DictDistribution. This would end up making UniformDistribution as its own class somewhat superfluous.

Thoughts @cgc ?

**Comment by cgc** [comment]
I don't have full context on our choices for Uniform/Deterministic distribution anymore, but my memory is I'd added them to help with performance (DeterministicDistribution is pretty critical for deterministic MDPs at the very least). Figured the best way to preserve some of the performance (by avoiding a dictionary lookup to get an associated probability) is to ensure elements are unique when passed into the constructor (by throwing an error when they are not), which I coded up in #60. I think this is a better idea than making the elements unique behind the scenes (since that might mask certain kinds of coding errors). LMK what you think

**Comment by markkho** [comment]
If the idea is for UniformDistribution to be more efficient, this fix could work. 

But this conversation is making me think: I've found it confusing that we have a `DictDistribution.uniform` constructor that returns something that isn't a `DictDistribution`. This seems to conflate constructing uniform distributions (an interface issue) with having fast methods for distributions known to be uniform (an optimization/implementation issue). I'm wondering if we should de-couple these by having a `UniformDistribution` implementation that optimized and used in special cases and have `DictDistribution.uniform` return a uniform `DictDistribution`. Right now it feels like we're splitting the baby.

Also, fwiw, I was curious and did some comparisons of runtimes with the following code:
```python
from msdm.core.distributions import UniformDistribution, DictDistribution

class UniformDistribution_nocheck(UniformDistribution):
    def __init__(self, support):
        self._support = support
        
class UniformDistribution_check_noflag(UniformDistribution):
    def __init__(self, support):
        self._support = set(support)
        assert len(self._support) == len(support), (
            f'Invalid support {self._support}: some event is duplicated.'
        )
        
class UniformDistribution_check_flag(UniformDistribution):
    def __init__(self, support, check_unique=True):
        if check_unique:
            self._support = set(support)
            assert len(self._support) == len(support), (
                f'Invalid support {self._support}: some event is duplicated.'
            )
        else:
            self._support = support
        
class UniformDistribution_dict(DictDistribution):
    def __init__(self, support):
        prob = 1/len(support)
        dist = {}
        for e in support:
            if e in dist:
                dist[e] += prob
            else:
                dist[e] = prob
        DictDistribution.__init__(self, dist)
```
And got these results:

![image](https://user-images.githubusercontent.com/3951436/167475196-104f04c4-2a82-4dd9-af7c-cc31fecefe85.png)

**Comment by cgc** [comment]
I think `DictDistribution.uniform` used to be a convenience function that inspired making `UniformDistribution` -- happy to deprecate/remove, though I think having both `.uniform() -> DictDistribution` and `UniformDistribution` is a bit confusing.

Adding `_checkflag` version to PR
