### ISSUE TITLE
[BUG] Q values are not initialized correctly 

### ISSUE THREAD

**Issue by zhouzypaul** [markkho/msdm#61]
Hi Mark! Thanks for building this library, I think it's really easy to use and convenient. 

I noticed I bug in the Q Learning algorithm though, where the Q values are queried as if they were initialized to 0, instead of the specified initialization value. This would be a problem where one uses Q values that are supposed to be optimistically initialized. 

I have submitted an easy fix via a PR.

**Comment by markkho** [comment]
Thanks Paul!

**Comment by markkho** [comment]
I just want to write a test case to make sure q initialization works and then i'll close this.

**Comment by markkho** [comment]
Caught another bug and added tests fbf2b4572baf2ed79289049cb0b7d3a0146efcb9
