### ISSUE TITLE
RMAX?

### ISSUE THREAD

**Issue by zhouzypaul** [markkho/msdm#63]
Hey Mark, is RMAX within the scope of this library? Specifically, I'm thinking about an RMAX for a TaburlarMarkovDecisionProcess, as described in Algorithm 1 [here](https://jmlr.org/papers/volume10/strehl09a/strehl09a.pdf).

**Comment by markkho** [comment]
Hey @zhouzypaul, having an implementation of RMAX would be great! What were you thinking in terms of the interface? Maybe something like what we did with TDLearning [here](https://github.com/markkho/msdm/blob/fbf2b4572baf2ed79289049cb0b7d3a0146efcb9/msdm/algorithms/tdlearning.py#L74) could work?

Based on a quick skim of Algorithm 1, maybe something like this could work (totally open to other ideas too) - what do you think?
```python
class RMAX(Learns):
   def __init__(
        self,
        episodes : int = 100,
        transition_samples : int = 100, # parameter m, could use a different name
        PlanningAlgorithm = ValueIteration,
        planning_algorithm_params = None, # might need to figure out how to set these by default based on the alg used
        exploration_bonus : float = ??? ,# parameter \epsilon_1 (don't totally understand what this does yet)
        initial_q : float = 0.0, # parameter U(s, a); could be a state-action function also
        seed : int = None,
        event_listener_class : EventListener = EpisodeRewardEventListener
    ):
```

**Comment by zhouzypaul** [comment]
yes that's what I'm imagining as well, just something that mirrors what TDLearning currently looks like. I already have an implementation, I will try to brush it up and make the interface soon.
