### ISSUE TITLE
A*: Throw error when heuristic is not admissible

### ISSUE THREAD

**Issue by cgc** [markkho/msdm#78]
We should add an option to A* search for planning to throw an error if the heuristic is found to be inadmissible.

**Comment by markkho** [comment]
That could be useful - just to be clear, users would have the option of using an inadmissible heuristic if they wanted? Also, would there be an overhead to checking inadmissibility?

**Comment by cgc** [comment]
Closing this since we've added a test for monotonicity (flag is `assert_monotone_heuristic`, added in #79) and testing admissibility is not a priority.
